### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by Keith94** [func0der/colorfulTabs#1]
Is there any chance you will continue updating this, or is this abandoned? The original version still has a lot of issues which probably won't be addressed any time soon by the original developer; it would be nice to have an actively maintained forked version here on GitHub.

**Comment by func0der** [comment]
I could update this, but I may not be allowed to distribute this: https://creativecommons.org/licenses/by-nc-nd/3.0/us/

I am not 100% sure about this, though. When does this work starts to be a derivate?

**Comment by Keith94** [comment]
Hmm, I'm not too familiar with that subject, I wish I could tell you.

I basically saw the current version of ColorfulTabs having many compatibility issues and such; for example the coloring based on tab favicon doesn't seem to work at all, I would also like an option to disable the ugly gradients and fix the white border colors, etc. I thought maybe you'd be able to fix these problems, to make it usable again.

Or as a (better?) alternative, there is also [ChromaTabs](https://addons.mozilla.org/en-US/firefox/search/?q=chromatabs) (and its forks) which has similar features, but could also use updating for modern versions.
